name: Deployment

on:
    workflow_dispatch:

jobs:
  linting:
    name: Lint Ansible files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: action/checkout@v2
    - name: Linting
      uses: ansible/ansible-lint-action@main
      with:
        targets: |
          ansible/playbook.yml
          ansible/inventory.yml