name: Deployment

on:
    workflow_dispatch:

jobs:
  linting:
    name: Lint Ansible files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: action/checkout@v2
    - name: Linting
      uses: ansible/ansible-lint-action@82d11c945e8f70cee5b30101f9de8ab11d89286a
        targets: |
          ansible/playbook.yml
          ansible/inventory.yml